### ISSUE TITLE
Design the styleguide

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-discussify#14]
Design the style guide with all the "Discussify - Browser Extension" components.

Acceptance criteria:

1. Styleguide is in agreed location.
2. Team has reviewed symbol names.
3. Any font or assets that require some license is signed off.

**Comment by satazor** [comment]
@andreforsousa please continuously update this issue with the latest version of the styleguide because I will be using this issue to link to others.

**Comment by andreforsousa** [comment]
@satazor the current version is here:
https://drive.google.com/drive/folders/1tAz3IeAlQ0a88SGw2Q1URdXyQ52b3Cia?usp=sharing

Already prepared slices for the iconography being used at the moment.

**Comment by satazor** [comment]
Cool, feel free to put the task into review.

**Comment by andreforsousa** [comment]
@satazor I've updated the file with the "Feedback Icons" and other minor fixes related with folders and symbols organization:
https://drive.google.com/drive/folders/1Y80dN0WqjJ9tfwyCuCOt_DqTGYrcBfpN?usp=sharing

**Comment by marcooliveira** [comment]
@andreforsousa let's move the styleguide to the repo, and then we close this.

**Comment by andreforsousa** [comment]
Updated styleguide, included the disable states for Colored background primary and secondary buttons. Also fixed color names and added "monza" (red) and "ripe-lemon" (yellow) considering the multiple error and warning scenarios.

Latest version here:
https://drive.google.com/drive/folders/1tajbF7bS1d5FExUHyUXawUvALbp9ceUf?usp=sharing

**Comment by marcooliveira** [comment]
Still missing acceptance criteria 3, specifically we need to buy the font license.

We're using *Avenir*, which can be acquired in one of the following links:

- https://www.myfonts.com/fonts/linotype/avenir
- https://www.fonts.com/font/linotype/avenir

I'm a bit worried with the licensing model that these services provide. There really isn't a font that is adequate to our needs, we'd probably need to get in touch to come to an agreement with them. For the time being, I would recommend trying to use a Google Font, and later on we can revisit if it's worth it. Let's try and find a similar font there first.
