### ISSUE TITLE
Define goals for Decentralised Web Summit

### ISSUE THREAD

**Issue by marcooliveira** [ipfs-shipyard/pm-discussify#40]
- Why are we presenting there?
- What are the features we expect to have by the summit?
- What do we want to communicate about the project?
- What do we expect to take out of this presentation?

Acceptance criteria:

- Have clear response for each of the questions above.
- Updated `README` on the project root, namely Roadmap.

@diasdavid, would be great if you could weigh in, thanks!

**Comment by satazor** [comment]
We have attended DWeb Summit but a lot of stuff happened. We focused on demoing out peer-star-app.

I will be updating the milestones as requested by @pgte as part of #42.
