### ISSUE TITLE
Create tween animation between FAB and sidebar

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-discussify#52]
@satazor Here's the example of overall speed, duration and morph for FAB and sidebar:
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1RJ1TKFFa6qwYLHOlmSvCvBguYlHGSUiM%2F01-tweening.mp4

This should be taken care afterwards since it is not a priority at this moment.

Thanks.

**Comment by satazor** [comment]
We now have a tween animation similar to the one in the video!
