### ISSUE TITLE
UI Animations to Polish Extension

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-discussify#66]
Here is the list of the animations we should tackle in order to give a more polished feel to the extension.

Ordered by priority:
- All actions triggered get a fade-in:
    - After clicking “REPLY”
    - After “CANCEL” a new reply
- Add transition with opacity once user clicks “EDIT” comment
- Animate “placeholder comment” content bars  
- Comments “skew”
- Add scale and subtle bounce to the FAB when opening the extension in the browsers
- Scale down and fade-out the FAB once the extension is closed
- Tween between FAB and sidebar as previously mentioned in #52. 
- After closing modal add Fade-out on modal and overlay

@marcooliveira @satazor @PedroMiguelSS

**Comment by satazor** [comment]
All of these animations were implemented and will be released soon.
