### ISSUE TITLE
Research about the publishing parameters

### ISSUE THREAD

**Issue by marcooliveira** [ipfs-shipyard/pm-discussify#67]
- [ ] Create copy and produce imagery (videos or pictures) for both Chrome and Firefox
- [x] Update README
  - Include dev install, for collaborating;
  - Normal install, for regular users/testers;
- [ ] Publish rights on both chrome and firefox stores

**Comment by marcooliveira** [comment]
Some relevant notes on publishing on both stores:

- Chrome: https://developer.chrome.com/webstore/publish
- Firefox: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on

**Comment by satazor** [comment]
We already submitted to the Chrome Store in December. Regarding Firefox, we will also be publishing soon, after @acostalima fixes a bug with the scroll there.

Closing this meanwhile.
