### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-discussify#68]
While publishing Discussify on Firefox store we got stuck due to a required privacy policy.

> If your add-on transmits any data from the user's computer, a privacy policy is required that explains what data is sent and how it is used.

Which seems to be our situation. My question is: do we already have a privacy policy for situations like this one?

@lidel suggested using a disclaimer stating that this is beta quality software for now and comes with no privacy guarantees.

What should we do? @daviddias @satazor @marcooliveira

**Comment by daviddias** [comment]
@lidel will be the person with a ton of experience to share light here :)

**Comment by satazor** [comment]
@lidel Yep I think it makes sense indeed. Can you send an email to the legal team with both Pedro, me and David in cc to kickstart the conversation? I don't know their emails and it would serve as mainly a "presentation" email.

**Comment by satazor** [comment]
We now have a initial version of the Privacy Policy here: https://github.com/ipfs-shipyard/pm-discussify
