### ISSUE TITLE
Check out this UX

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/pm-discussify#69]
@gozala just shared an hypothesis url and it blown my mind. See:

https://github.com/ipfs/interface-ipfs-core/issues/284#issuecomment-445585271
https://via.hypothes.is/https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/1211152/49711922-f9423000-fc39-11e8-9700-77c65fb9cfd9.png">

It would be great to have discussify import Web Annotation threads and provide the convo to happen over the DWeb :)

**Comment by Gozala** [comment]
I also have being working on hypothesis client fork that replaces backend with Dat storage (mostly for use in beaker). Trying IPFS version was also on the back of my mind. I was not aware of Discussify but I'd absolutely love something like hypothesis where I got to own my data.

**Comment by satazor** [comment]
We are going to definitively embrace web annotations, it's actually a feature in our [v1.0.0](https://github.com/ipfs-shipyard/pm-discussify#v100) release. As part of the feature, we could add the ability to import web annotation datasets.
